import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { Navbar } from '@/components/navbar';
import {
  Compass,
  Sparkles,
  Clock,
  Layers,
  ArrowRight,
  GitFork,
  BookOpen,
} from 'lucide-react';
import { FadeIn, StaggerContainer, StaggerItem, CardHover } from '@/components/animations/motion-components';
import type { Database } from '@/lib/supabase/types';

export const metadata = {
  title: 'Explore Community Courses – LearnStratum',
  description: 'Browse, learn from, and fork public courses generated by the LearnStratum community.',
};

type CourseRow = Database['public']['Tables']['courses']['Row'];

export default async function ExplorePage() {
  const supabase = await createClient();

  // Fetch all public courses with modules and lessons count
  const { data: coursesData } = await supabase
    .from('courses')
    .select(`
      id,
      title,
      description,
      topic,
      difficulty_level,
      weekly_hours_allocated,
      slug,
      created_at,
      modules (
        id,
        lessons (id)
      )
    `)
    .eq('is_public', true)
    .order('created_at', { ascending: false });

  const courses = (coursesData ?? []).map((c: any) => {
    const modules = c.modules ?? [];
    const lessonCount = modules.reduce(
      (acc: number, m: any) => acc + (m.lessons?.length || 0),
      0
    );
    return {
      ...c,
      moduleCount: modules.length,
      lessonCount,
    };
  });

  return (
    <div className="min-h-screen flex flex-col bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 transition-colors">
      <Navbar />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
        {/* Hero Banner */}
        <FadeIn direction="up">
          <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-900 via-indigo-950 to-zinc-950 text-white p-8 sm:p-12 border border-indigo-800/40 shadow-xl">
            <div className="absolute top-0 right-0 -mt-12 -mr-12 w-96 h-96 rounded-full bg-indigo-500/10 blur-3xl pointer-events-none" />
            <div className="relative max-w-2xl space-y-4">
              <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-indigo-500/20 border border-indigo-400/30 text-indigo-300 text-xs font-semibold">
                <Compass className="w-3.5 h-3.5" />
                <span>Community Syllabus Hub</span>
              </div>
              <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight">
                Explore & Fork Courses
              </h1>
              <p className="text-sm sm:text-base text-zinc-300 leading-relaxed">
                Discover curated curricula built by fellow learners. Fork any course directly into your personal workspace with automated spaced repetition and interactive quizzes.
              </p>
            </div>
          </div>
        </FadeIn>

        {/* Course Grid */}
        <div className="space-y-6">
          <FadeIn direction="up" delay={0.1}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                <h2 className="text-xl font-bold tracking-tight text-zinc-900 dark:text-zinc-100">
                  Public Curricula ({courses.length})
                </h2>
              </div>
            </div>
          </FadeIn>

          {courses.length === 0 ? (
            <FadeIn direction="up" delay={0.15}>
              <div className="p-12 text-center rounded-3xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 space-y-4">
                <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 flex items-center justify-center mx-auto">
                  <Sparkles className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-bold text-zinc-900 dark:text-white">
                  No public courses yet
                </h3>
                <p className="text-sm text-zinc-500 max-w-md mx-auto">
                  Be the first to share! Create a course from your dashboard and toggle its visibility to Public.
                </p>
                <Link
                  href="/courses/new"
                  className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold shadow-sm transition"
                >
                  <span>Create Course</span>
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </FadeIn>
          ) : (
            <StaggerContainer className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {courses.map((course: any) => {
                const targetUrl = course.slug ? `/explore/${course.slug}` : `/courses/${course.id}`;
                return (
                  <StaggerItem key={course.id}>
                    <CardHover className="h-full">
                      <div className="flex flex-col justify-between p-6 rounded-3xl bg-white dark:bg-zinc-900 border border-zinc-200/80 dark:border-zinc-800 shadow-sm hover:shadow-md hover:border-indigo-200 dark:hover:border-indigo-900 transition-all duration-200 group h-full">
                        <div className="space-y-4">
                          {/* Topic & Difficulty */}
                          <div className="flex flex-wrap items-center justify-between gap-2">
                            <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-50 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300">
                              <Sparkles className="w-3 h-3" />
                              {course.topic}
                            </span>
                            <span className="text-[11px] font-medium px-2 py-0.5 rounded-md bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 capitalize">
                              {course.difficulty_level}
                            </span>
                          </div>

                          {/* Title & Description */}
                          <div>
                            <h3 className="text-lg font-bold text-zinc-900 dark:text-white group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors line-clamp-1">
                              {course.title}
                            </h3>
                            {course.description && (
                              <p className="mt-1.5 text-xs text-zinc-500 line-clamp-2 leading-relaxed">
                                {course.description}
                              </p>
                            )}
                          </div>

                          {/* Stats */}
                          <div className="flex items-center gap-4 text-xs text-zinc-400 pt-2 border-t border-zinc-100 dark:border-zinc-800/80">
                            <span className="flex items-center gap-1.5">
                              <Layers className="w-3.5 h-3.5 text-zinc-500" />
                              {course.moduleCount} modules ({course.lessonCount} lessons)
                            </span>
                            <span className="flex items-center gap-1.5">
                              <Clock className="w-3.5 h-3.5 text-zinc-500" />
                              {course.weekly_hours_allocated}h/wk
                            </span>
                          </div>
                        </div>

                        {/* Action buttons */}
                        <div className="mt-6 pt-4 border-t border-zinc-100 dark:border-zinc-800/80 flex items-center justify-between gap-3">
                          <Link
                            href={targetUrl}
                            className="inline-flex items-center gap-1.5 text-xs font-bold text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 transition"
                          >
                            <span>View Syllabus</span>
                            <ArrowRight className="w-3.5 h-3.5" />
                          </Link>

                          <Link
                            href={targetUrl}
                            className="inline-flex items-center gap-1 px-3 py-1.5 rounded-xl bg-zinc-100 dark:bg-zinc-800 hover:bg-indigo-50 dark:hover:bg-indigo-950/40 text-zinc-700 dark:text-zinc-300 hover:text-indigo-600 dark:hover:text-indigo-300 text-xs font-semibold transition"
                          >
                            <GitFork className="w-3.5 h-3.5" />
                            <span>Fork</span>
                          </Link>
                        </div>
                      </div>
                    </CardHover>
                  </StaggerItem>
                );
              })}
            </StaggerContainer>
          )}
        </div>
      </main>
    </div>
  );
}
